# Generated by Django 4.2 on 2023-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="session_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="session_url",
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
