# Generated by Django 4.2 on 2023-04-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0002_initial"),
        (
            "payments",
            "0002_remove_payment_session_id_remove_payment_session_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="borrowing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="borrowings.borrowing",
            ),
        ),
    ]
